name: Cyber chat CI
on:
  push:
    paths-ignore: ["**.md", "docs/**"]
  pull-request:
    branches: [main]
jobs:
  lint:
    runs_on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup node
        uses: actions/setup-node@v6
      
      - name: Install & lint
        run: npm ci && npm lint

